# ========================================
# EXAMPLE PYTHON TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "src"

[python-piprot]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "low"

[python-safety]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "medium"

[trufflehog]
SOURCE = ["."]
EXCLUDE = [
    ".*(node_modules|target|build|dist)$",
    ".*\\.(jpe?g|png|svg|eot|ttf|exe|map|lock|woff|pytest_cache)$",
    ".*//trufflehog-report.json$",
    ".*\\.DS_Store",
    "tests/"
]

[trufflehog.ci]
INCLUDE_FULL_REASON = false

[python-cyclonedx]
REQUIREMENTS_FILE = "requirements.txt"

# ========================================
# REPORT CONFIG
# ========================================
[eze]
CONSOLE_ENDPOINT = "https://aio7y6esb7.execute-api.eu-west-2.amazonaws.com/development"

[console]
PRINT_SUMMARY_ONLY = true

[json]
REPORT_FILE = "reports/eze_report.json"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["python-piprot", "python-bandit", "python-safety", "python-cyclonedx", "trufflehog"]
reporters = ["json", "console", "bom"]

[scan.linux]
tools = ["python-piprot", "python-bandit", "semgrep", "python-safety", "python-cyclonedx", "trufflehog"]
reporters = ["json", "console", "bom"]

[scan.ci]
tools = ["python-piprot", "python-bandit", "python-safety", "python-cyclonedx", "trufflehog:ci"]
reporters = ["console", "eze"]
